/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchTransferResponseV1 } from './achTransferResponseV1';

export interface AchBatchTransferResponseV1 {
  id: string;
  state: AchBatchTransferResponseV1State;
  transferType: AchBatchTransferResponseV1TransferType;
  batchTransferId: string;
  totalAmount: number;
  metadata: any;
  webhookClientURL?: string;
  transfers: Array<AchTransferResponseV1>;
}
export enum AchBatchTransferResponseV1State {
  Pending = 'pending',
  Processing = 'processing',
  Completed = 'completed',
}
export enum AchBatchTransferResponseV1TransferType {
  Regular = 'regular',
  Expedite = 'expedite',
  Ach = 'ach',
  Rtp = 'rtp',
}
