/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchTransferAuditResponseV1 } from './achTransferAuditResponseV1';

export interface AchTransferResponseV1 {
  id: string;
  state: AchTransferResponseV1State;
  amount: number;
  direction: AchTransferResponseV1Direction;
  paymentType: AchTransferResponseV1PaymentType;
  paymentProvider: string;
  originatingAccountId: string;
  receivingAccountId: string;
  modernTreasuryPaymentOrderId?: string;
  trails?: Array<AchTransferAuditResponseV1>;
}
export enum AchTransferResponseV1State {
  Pending = 'pending',
  Processing = 'processing',
  Sent = 'sent',
  Completed = 'completed',
  Failed = 'failed',
}
export enum AchTransferResponseV1Direction {
  Credit = 'credit',
  Debit = 'debit',
}
export enum AchTransferResponseV1PaymentType {
  Rtp = 'rtp',
  Wire = 'wire',
  Ach = 'ach',
}
