/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PlaidTransferDto {
  /**
   * The url of client webhook where the transfer latest status will be send
   */
  webhook_client_url?: string;
  /**
   * The Plaid access_token for the account that will be debited or credited
   */
  access_token: string;
  /**
   * The Plaid account id corresponding to the end-user account that will be debited or credited. Required when creating a transfer
   */
  account_id: string;
  /**
   * The amount of the transfer (decimal string with two digits of precision)
   */
  amount: string;
  /**
   * The type of transfer. This will be either debit or credit.
   */
  type: string;
  /**
   * The transfer description. Maximum of 15 characters
   */
  description: string;
  /**
   * The legal user for the account holder.
   */
  user: object;
  /**
   * Information about the device being used to initiate the authorization
   */
  device?: object;
}
