/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PlaidTransferResponse {
  /**
   * The url of client webhook where the transfer latest status will be send
   */
  webhook_client_url?: string;
  /**
   * Unique identifier for a transfer. It is the same id Plaid returns
   */
  id: string;
  /**
   * The Plaid account id corresponding to the end-user account that will be debited or credited. Required when creating a transfer
   */
  account_id: string;
  /**
   * The amount of the transfer (decimal string with two digits of precision)
   */
  amount: string;
  /**
   * The transfer description. Maximum of 15 characters
   */
  description: string;
  /**
   * The status of the transfer. Possible values: pending, posted, settled, cancelled, failed, returned
   */
  status?: PlaidStatus;
  /**
   * Idempotency key.
   */
  idempotency_key: string;
  /**
   * The type of transfer. This will be either debit or credit.
   */
  type: string;
  /**
   * A decision regarding the proposed transfer. Possible values: approved, declined
   */
  decision?: string;
  /**
   * The rationale for Plaid decision regarding a proposed transfer. It is always set for declined decisions, and may or may not be null for approved decisions.
   */
  decision_rationale?: string;
  /**
   * The failure reason if the event type for a transfer is \"failed\" or \"returned\". Null value otherwise.
   */
  failure_reason: object;
  /**
   * The legal user for the account holder.
   */
  user: object;
  /**
   * Information about the device being used to initiate the authorization
   */
  device?: object;
}

export enum PlaidStatus {
  Pending = 'pending', //new transfer was created
  Posted = 'posted', //transfer has been successfully submitted to the payment network
  Settled = 'settled', //debits have been deducted
  Canceled = 'cancelled', //transfer was cancelled
  Failed = 'failed', //transfer failed
  Returned = 'returned', //transfer was returned.
}
