/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RtpPaymentDto {
  /**
   * Payment amount $10 would be represented as 1000 (cents).
   */
  amount: number;
  /**
   * The account id from where the amount will be transfered
   */
  originatingAccountId: string;
  /**
   * The account id where the amount will be received
   */
  receivingAccountId: string;
  /**
   * The name of the receiving bank
   */
  receivingBankName?: string;
}
