/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferAuditResponseV1 } from './transferAuditResponseV1';

export interface TransferResponseV1 {
  id: string;
  state: TransferResponseV1State;
  amount: number;
  direction: TransferResponseV1Direction;
  paymentType: TransferResponseV1PaymentType;
  paymentProvider: string;
  originatingAccountId: string;
  receivingAccountId: string;
  createdAt: string;
  failureReason: string;
  modernTreasuryPaymentOrderId?: string;
  fallbackForTransferId?: string;
  fallbackWithTransferId?: string;
  trails?: Array<TransferAuditResponseV1>;
}
export enum TransferResponseV1State {
  Pending = 'pending',
  Processing = 'processing',
  Sent = 'sent',
  Completed = 'completed',
  Failed = 'failed',
}
export enum TransferResponseV1Direction {
  Credit = 'credit',
  Debit = 'debit',
}
export enum TransferResponseV1PaymentType {
  Rtp = 'rtp',
  Wire = 'wire',
  Ach = 'ach',
}
