/**
 * Transfers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TransferAuditResponseV1 {
  id: string;
  state: TransferAuditResponseV1State;
  paymentType?: TransferAuditResponseV1PaymentType;
  paymentProvider: string;
  paymentProviderPaymentId?: string;
  paymentProviderPaymentStatus?: string;
  paymentProviderRequestTransportStatus?: string;
  fallbackForTransferId?: string;
  fallbackWithTransferId?: string;
}
export enum TransferAuditResponseV1State {
  Pending = 'pending',
  Processing = 'processing',
  Sent = 'sent',
  Completed = 'completed',
  Failed = 'failed',
}
export enum TransferAuditResponseV1PaymentType {
  Rtp = 'rtp',
  Wire = 'wire',
  Ach = 'ach',
}
