import { DatabaseModule } from '@module-database';
import { Module } from '@nestjs/common';
import {
  ActivityLogRepository,
  AuditLogRepository,
  BrokerFactoringConfigRepository,
  BrokerFactoringStatsRepository,
  BrokerPaymentRepository,
  ClientBatchPaymentRepository,
  ClientBrokerAssignmentAssocRepository,
  ClientBrokerAssignmentRepository,
  ClientFactoringAnalyticsRepository,
  ClientFactoringConfigsRepository,
  ClientFactoringRateReasonAssocRepository,
  ClientFactoringRateReasonRepository,
  ClientPaymentRepository,
  PaymentOrderRepository,
  ClientReserveRateReasonRepository,
  ClientReseveRateReasonAssocRepository,
  ClientStatusReasonAssocRepository,
  ClientStatusReasonConfigRepository,
  ClientSuccessTeamRepository,
  ClientTagRepository,
  EmailRepository,
  EmployeeRepository,
  FactoringCompanyRepository,
  FirebaseTokenRepository,
  InvoiceClientPaymentRepository,
  InvoiceDocumentRepository,
  InvoiceHistoryRepository,
  InvoiceRepository,
  MaintenanceRepository,
  NotificationRepository,
  PendingBuyoutRepository,
  PendingBuyoutsBatchRepository,
  PeruseRepository,
  ProcessingNotesRepository,
  QuickbooksAccountsRepository,
  QuickbooksTokensRepository,
  QuickbooksJournalEntryRepository,
  ReportDocumentRepository,
  Repositories,
  RequestStorageRepository,
  ReserveAccountFundsRepository,
  ReserveBrokerPaymentRepository,
  ReserveClientPaymentRepository,
  ReserveInvoiceRepository,
  ReserveRepository,
  TagDefinitionGroupRepository,
  TagDefinitionRepository,
  UserRepository,
  WorkerJobRepository,
} from './repositories';
import { CommonModule } from '../common';

const repositories = [
  ActivityLogRepository,
  AuditLogRepository,
  BrokerFactoringStatsRepository,
  BrokerPaymentRepository,
  ClientBatchPaymentRepository,
  ClientBrokerAssignmentRepository,
  ClientFactoringAnalyticsRepository,
  ClientFactoringConfigsRepository,
  ClientFactoringRateReasonAssocRepository,
  ClientFactoringRateReasonRepository,
  ClientPaymentRepository,
  ClientReserveRateReasonRepository,
  ClientReseveRateReasonAssocRepository,
  ClientStatusReasonAssocRepository,
  ClientStatusReasonConfigRepository,
  ClientSuccessTeamRepository,
  ClientTagRepository,
  PaymentOrderRepository,
  ProcessingNotesRepository,
  FactoringCompanyRepository,
  InvoiceClientPaymentRepository,
  InvoiceDocumentRepository,
  InvoiceHistoryRepository,
  InvoiceRepository,
  MaintenanceRepository,
  NotificationRepository,
  PendingBuyoutRepository,
  PendingBuyoutsBatchRepository,
  PeruseRepository,
  RequestStorageRepository,
  ReserveAccountFundsRepository,
  ReserveBrokerPaymentRepository,
  ReserveClientPaymentRepository,
  ReserveInvoiceRepository,
  ReserveRepository,
  TagDefinitionGroupRepository,
  TagDefinitionRepository,
  UserRepository,
  BrokerFactoringConfigRepository,
  WorkerJobRepository,
  ReportDocumentRepository,
  ClientBrokerAssignmentAssocRepository,
  EmployeeRepository,
  FirebaseTokenRepository,
  EmailRepository,
  QuickbooksAccountsRepository,
  QuickbooksJournalEntryRepository,
  QuickbooksTokensRepository,
];

@Module({
  imports: [DatabaseModule, CommonModule],
  providers: [...repositories, Repositories],
  exports: [...repositories, Repositories],
})
export class PersistenceModule {}
